/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import server.Server;

/**
 *
 * @author pavle
 */
public class ServerskaForma extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ServerskaForma.class.getName());

    /**
     * Creates new form ServerskaForma
     */
    private Server server;
    
    public ServerskaForma() {
        initComponents();
        setLocationRelativeTo(null);
        server = new Server();
        btnZaustavi.setEnabled(false);
        lblStatus.setText("Server nije pokrenut.");
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                server.zaustaviServer();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPokreni = new javax.swing.JButton();
        btnZaustavi = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuKonfiguracija = new javax.swing.JMenu();
        konfiguracijaBaze = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPokreni.setText("Pokreni Server");
        btnPokreni.addActionListener(this::btnPokreniActionPerformed);

        btnZaustavi.setText("Zaustavi Server");
        btnZaustavi.setEnabled(false);
        btnZaustavi.addActionListener(this::btnZaustaviActionPerformed);

        lblStatus.setText("jLabel1");

        menuKonfiguracija.setText("Konfiguracija");

        konfiguracijaBaze.setText("Konfiguracija Baze");
        konfiguracijaBaze.addActionListener(this::konfiguracijaBazeActionPerformed);
        menuKonfiguracija.add(konfiguracijaBaze);

        jMenuBar1.add(menuKonfiguracija);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatus)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPokreni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnZaustavi)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(lblStatus)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPokreni)
                    .addComponent(btnZaustavi))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void konfiguracijaBazeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konfiguracijaBazeActionPerformed
        FormaKonfBaza forma = new FormaKonfBaza();
        forma.setLocationRelativeTo(this);
        forma.setVisible(true);
        if (server.isKraj()) {
            server = new Server();
        }
        osveziStatus();
    }//GEN-LAST:event_konfiguracijaBazeActionPerformed

    private void btnPokreniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokreniActionPerformed
        btnPokreni.setEnabled(false);
        btnZaustavi.setEnabled(true);
        konfiguracijaBaze.setEnabled(false);
        lblStatus.setText("Server se pokrece...");

        Thread thread = new Thread(() -> {
            try {
                server.run();
            } finally {
                javax.swing.SwingUtilities.invokeLater(() -> {
                    osveziStatus();
                    btnPokreni.setEnabled(true);
                    btnZaustavi.setEnabled(false);
                    konfiguracijaBaze.setEnabled(true);
                });
            }
        }, "Server-Main-Thread");
        thread.start();

        lblStatus.setText("Server je pokrenut.");
    }//GEN-LAST:event_btnPokreniActionPerformed

    private void btnZaustaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZaustaviActionPerformed
        server.zaustaviServer();
        btnPokreni.setEnabled(true);
        btnZaustavi.setEnabled(false);
        server = new Server();
        konfiguracijaBaze.setEnabled(true);
        osveziStatus();
    }//GEN-LAST:event_btnZaustaviActionPerformed

    private void osveziStatus() {
        if (server != null && !server.isKraj()) {
            lblStatus.setText("Server je pokrenut.");
        } else {
            lblStatus.setText("Server nije pokrenut.");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPokreni;
    private javax.swing.JButton btnZaustavi;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem konfiguracijaBaze;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JMenu menuKonfiguracija;
    // End of variables declaration//GEN-END:variables
}
