/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import javax.swing.JButton;

/**
 *
 * @author pavle
 */
public class GlavnaForma extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GlavnaForma.class.getName());

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnKreirajRacun = new javax.swing.JButton();
        btnPretraziRacun = new javax.swing.JButton();
        btnPretraziKupca = new javax.swing.JButton();
        btnKreirajKupca = new javax.swing.JButton();
        btnUbaciSmenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnKreirajRacun.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnKreirajRacun.setText("Kreiraj račun");

        btnPretraziRacun.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnPretraziRacun.setText("Pretraži račun");

        btnPretraziKupca.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnPretraziKupca.setText("Pretraži kupca");

        btnKreirajKupca.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnKreirajKupca.setText("Kreiraj kupca");

        btnUbaciSmenu.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnUbaciSmenu.setText("Ubaci smenu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnKreirajKupca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUbaciSmenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPretraziKupca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 958, Short.MAX_VALUE))
                    .addComponent(btnPretraziRacun, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
                    .addComponent(btnKreirajRacun, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 125, Short.MAX_VALUE)
                .addComponent(btnKreirajRacun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPretraziRacun)
                .addGap(42, 42, 42)
                .addComponent(btnKreirajKupca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPretraziKupca)
                .addGap(53, 53, 53)
                .addComponent(btnUbaciSmenu)
                .addGap(0, 125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnKreirajKupca() {
        return btnKreirajKupca;
    }

    public void setBtnKreirajKupca(JButton btnKreirajKupca) {
        this.btnKreirajKupca = btnKreirajKupca;
    }

    public JButton getBtnKreirajRacun() {
        return btnKreirajRacun;
    }

    public void setBtnKreirajRacun(JButton btnKreirajRacun) {
        this.btnKreirajRacun = btnKreirajRacun;
    }

    public JButton getBtnPretraziKupca() {
        return btnPretraziKupca;
    }

    public void setBtnPretraziKupca(JButton btnPretraziKupca) {
        this.btnPretraziKupca = btnPretraziKupca;
    }

    public JButton getBtnPretraziRacun() {
        return btnPretraziRacun;
    }

    public void setBtnPretraziRacun(JButton btnPretraziRacun) {
        this.btnPretraziRacun = btnPretraziRacun;
    }

    public JButton getBtnUbaciSmenu() {
        return btnUbaciSmenu;
    }

    public void setBtnUbaciSmenu(JButton btnUbaciSmenu) {
        this.btnUbaciSmenu = btnUbaciSmenu;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKreirajKupca;
    private javax.swing.JButton btnKreirajRacun;
    private javax.swing.JButton btnPretraziKupca;
    private javax.swing.JButton btnPretraziRacun;
    private javax.swing.JButton btnUbaciSmenu;
    // End of variables declaration//GEN-END:variables
}
