/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author pavle
 */
public class KreirajRacunForma extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KreirajRacunForma.class.getName());

    /**
     * Creates new form KreirajRacunForma
     */
    public KreirajRacunForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbProdavac = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbKupac = new javax.swing.JComboBox<>();
        panelStavke = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cmbGitara = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtCenaStavke = new javax.swing.JTextField();
        txtKolicinaStavke = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtIznosStavke = new javax.swing.JTextField();
        btnDodajStavku = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavkeRacuna = new javax.swing.JTable();
        btnObrisiStavku = new javax.swing.JButton();
        btnPromeniStavku = new javax.swing.JButton();
        btnIzaberiGitaru = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtDatumIzdavanja = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbNacinPlacanja = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtPopust = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtUkupanIznos = new javax.swing.JTextField();
        btnKreirajRacun = new javax.swing.JButton();
        btnNazad = new javax.swing.JButton();
        btnIzaberiKupca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Prodavac:");

        cmbProdavac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Kupac:");

        cmbKupac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        panelStavke.setBorder(javax.swing.BorderFactory.createTitledBorder("Stavke računa"));
        panelStavke.setToolTipText("");
        panelStavke.setName(""); // NOI18N

        jLabel7.setText("Gitara:");

        cmbGitara.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Cena stavke:");

        jLabel9.setText("Količina stavke:");

        jLabel10.setText("Iznos stavke:");

        btnDodajStavku.setText("Dodaj stavku");

        tblStavkeRacuna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavkeRacuna);

        btnObrisiStavku.setText("Obriši stavku");

        btnPromeniStavku.setText("Promeni stavku");

        btnIzaberiGitaru.setText("Izaberi gitaru");

        javax.swing.GroupLayout panelStavkeLayout = new javax.swing.GroupLayout(panelStavke);
        panelStavke.setLayout(panelStavkeLayout);
        panelStavkeLayout.setHorizontalGroup(
            panelStavkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStavkeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelStavkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelStavkeLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelStavkeLayout.createSequentialGroup()
                        .addGroup(panelStavkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelStavkeLayout.createSequentialGroup()
                                .addGroup(panelStavkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(panelStavkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbGitara, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCenaStavke)
                                    .addComponent(txtKolicinaStavke)
                                    .addComponent(txtIznosStavke, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnIzaberiGitaru))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelStavkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPromeniStavku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnObrisiStavku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDodajStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panelStavkeLayout.setVerticalGroup(
            panelStavkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelStavkeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelStavkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelStavkeLayout.createSequentialGroup()
                        .addGroup(panelStavkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cmbGitara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIzaberiGitaru)
                        .addGap(16, 16, 16)
                        .addGroup(panelStavkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCenaStavke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelStavkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKolicinaStavke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(panelStavkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtIznosStavke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelStavkeLayout.createSequentialGroup()
                        .addComponent(btnPromeniStavku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnObrisiStavku)
                        .addGap(6, 6, 6)
                        .addComponent(btnDodajStavku)))
                .addContainerGap())
        );

        jLabel3.setText("Datum izdavanja:");

        jLabel4.setText("Način plaćanja:");

        cmbNacinPlacanja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Popust:");

        jLabel6.setText("Ukupan iznos:");

        btnKreirajRacun.setText("Kreiraj račun");

        btnNazad.setText("Nazad");

        btnIzaberiKupca.setText("Izaberi kupca");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelStavke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbProdavac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbKupac, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnIzaberiKupca))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUkupanIznos)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDatumIzdavanja)
                                    .addComponent(cmbNacinPlacanja, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPopust, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnNazad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKreirajRacun)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbProdavac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtDatumIzdavanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbKupac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(cmbNacinPlacanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPopust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btnIzaberiKupca))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelStavke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKreirajRacun)
                    .addComponent(btnNazad))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnDodajStavku() {
        return btnDodajStavku;
    }

    public void setBtnDodajStavku(JButton btnDodajStavku) {
        this.btnDodajStavku = btnDodajStavku;
    }

    public JButton getBtnKreirajRacun() {
        return btnKreirajRacun;
    }

    public void setBtnKreirajRacun(JButton btnKreirajRacun) {
        this.btnKreirajRacun = btnKreirajRacun;
    }

    public JButton getBtnNazad() {
        return btnNazad;
    }

    public void setBtnNazad(JButton btnNazad) {
        this.btnNazad = btnNazad;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JPanel getPanelStavke() {
        return panelStavke;
    }

    public void setPanelStavke(JPanel panelStavke) {
        this.panelStavke = panelStavke;
    }

    public JTextField getTxtCenaStavke() {
        return txtCenaStavke;
    }

    public void setTxtCenaStavke(JTextField txtCenaStavke) {
        this.txtCenaStavke = txtCenaStavke;
    }

    public JTextField getTxtDatumIzdavanja() {
        return txtDatumIzdavanja;
    }

    public void setTxtDatumIzdavanja(JTextField txtDatumIzdavanja) {
        this.txtDatumIzdavanja = txtDatumIzdavanja;
    }

    public JTextField getTxtIznosStavke() {
        return txtIznosStavke;
    }

    public void setTxtIznosStavke(JTextField txtIznosStavke) {
        this.txtIznosStavke = txtIznosStavke;
    }

    public JTextField getTxtKolicinaStavke() {
        return txtKolicinaStavke;
    }

    public void setTxtKolicinaStavke(JTextField txtKolicinaStavke) {
        this.txtKolicinaStavke = txtKolicinaStavke;
    }

    public JTextField getTxtPopust() {
        return txtPopust;
    }

    public void setTxtPopust(JTextField txtPopust) {
        this.txtPopust = txtPopust;
    }

    public JTextField getTxtUkupanIznos() {
        return txtUkupanIznos;
    }

    public void setTxtUkupanIznos(JTextField txtUkupanIznos) {
        this.txtUkupanIznos = txtUkupanIznos;
    }

    public JComboBox<Object> getCmbGitara() {
        return cmbGitara;
    }

    public void setCmbGitara(JComboBox<Object> cmbGitara) {
        this.cmbGitara = cmbGitara;
    }

    public JComboBox<Object> getCmbKupac() {
        return cmbKupac;
    }

    public void setCmbKupac(JComboBox<Object> cmbKupac) {
        this.cmbKupac = cmbKupac;
    }

    public JComboBox<Object> getCmbNacinPlacanja() {
        return cmbNacinPlacanja;
    }

    public void setCmbNacinPlacanja(JComboBox<Object> cmbNacinPlacanja) {
        this.cmbNacinPlacanja = cmbNacinPlacanja;
    }

    public JComboBox<Object> getCmbProdavac() {
        return cmbProdavac;
    }

    public void setCmbProdavac(JComboBox<Object> cmbProdavac) {
        this.cmbProdavac = cmbProdavac;
    }

    public JTable getTblStavkeRacuna() {
        return tblStavkeRacuna;
    }

    public void setTblStavkeRacuna(JTable tblStavkeRacuna) {
        this.tblStavkeRacuna = tblStavkeRacuna;
    }

    public JButton getBtnObrisiStavku() {
        return btnObrisiStavku;
    }

    public void setBtnObrisiStavku(JButton btnObrisiStavku) {
        this.btnObrisiStavku = btnObrisiStavku;
    }

    public JButton getBtnPromeniStavku() {
        return btnPromeniStavku;
    }

    public void setBtnPromeniStavku(JButton btnPromeniStavku) {
        this.btnPromeniStavku = btnPromeniStavku;
    }

    public JButton getBtnIzaberiGitaru() {
        return btnIzaberiGitaru;
    }

    public void setBtnIzaberiGitaru(JButton btnIzaberiGitaru) {
        this.btnIzaberiGitaru = btnIzaberiGitaru;
    }

    public JButton getBtnIzaberiKupca() {
        return btnIzaberiKupca;
    }

    public void setBtnIzaberiKupca(JButton btnIzaberiKupca) {
        this.btnIzaberiKupca = btnIzaberiKupca;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStavku;
    private javax.swing.JButton btnIzaberiGitaru;
    private javax.swing.JButton btnIzaberiKupca;
    private javax.swing.JButton btnKreirajRacun;
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnObrisiStavku;
    private javax.swing.JButton btnPromeniStavku;
    private javax.swing.JComboBox<Object> cmbGitara;
    private javax.swing.JComboBox<Object> cmbKupac;
    private javax.swing.JComboBox<Object> cmbNacinPlacanja;
    private javax.swing.JComboBox<Object> cmbProdavac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelStavke;
    private javax.swing.JTable tblStavkeRacuna;
    private javax.swing.JTextField txtCenaStavke;
    private javax.swing.JTextField txtDatumIzdavanja;
    private javax.swing.JTextField txtIznosStavke;
    private javax.swing.JTextField txtKolicinaStavke;
    private javax.swing.JTextField txtPopust;
    private javax.swing.JTextField txtUkupanIznos;
    // End of variables declaration//GEN-END:variables
}
