/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author pavle
 */
public class PrikaziKupcaForma extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrikaziKupcaForma.class.getName());

    /**
     * Creates new form PrikaziKupcaForma
     */
    public PrikaziKupcaForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblKupac = new javax.swing.JTable();
        btnPromeniKupca = new javax.swing.JButton();
        btnObrisiKupca = new javax.swing.JButton();
        btnNazad = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtImePrezime = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbMuzickoObrazovanje = new javax.swing.JComboBox<>();
        btnPretraziKupca = new javax.swing.JButton();
        btnPrikaziKupca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblKupac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKupac);

        btnPromeniKupca.setText("Promeni izabranog kupca");

        btnObrisiKupca.setText("Obriši izabranog kupca");

        btnNazad.setText("Nazad");

        jLabel1.setText("Ime i prezime:");

        jLabel2.setText("Muzičko obrazovanje:");

        cmbMuzickoObrazovanje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnPretraziKupca.setText("Pretraži kupce");

        btnPrikaziKupca.setText("Prikaži izabranog kupca");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbMuzickoObrazovanje, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(53, 53, 53)
                        .addComponent(txtImePrezime))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnNazad)
                                .addGap(138, 138, 138)
                                .addComponent(btnPromeniKupca))
                            .addComponent(btnPretraziKupca, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnPrikaziKupca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnObrisiKupca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtImePrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbMuzickoObrazovanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnPretraziKupca)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btnPrikaziKupca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnObrisiKupca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPromeniKupca)
                    .addComponent(btnNazad))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnNazad() {
        return btnNazad;
    }

    public void setBtnNazad(JButton btnNazad) {
        this.btnNazad = btnNazad;
    }

    public JButton getBtnObrisiKupca() {
        return btnObrisiKupca;
    }

    public void setBtnObrisiKupca(JButton btnObrisiKupca) {
        this.btnObrisiKupca = btnObrisiKupca;
    }

    public JButton getBtnPromeniKupca() {
        return btnPromeniKupca;
    }

    public void setBtnPromeniKupca(JButton btnPromeniKupca) {
        this.btnPromeniKupca = btnPromeniKupca;
    }

    public JTable getTblKupac() {
        return tblKupac;
    }

    public void setTblKupac(JTable tblKupac) {
        this.tblKupac = tblKupac;
    }

    public JButton getBtnPretraziKupca() {
        return btnPretraziKupca;
    }

    public void setBtnPretraziKupca(JButton btnPretraziKupca) {
        this.btnPretraziKupca = btnPretraziKupca;
    }

    public JComboBox<Object> getCmbMuzickoObrazovanje() {
        return cmbMuzickoObrazovanje;
    }

    public void setCmbMuzickoObrazovanje(JComboBox<Object> cmbMuzickoObrazovanje) {
        this.cmbMuzickoObrazovanje = cmbMuzickoObrazovanje;
    }

    public JTextField getTxtImePrezime() {
        return txtImePrezime;
    }

    public void setTxtImePrezime(JTextField txtImePrezime) {
        this.txtImePrezime = txtImePrezime;
    }

    public JButton getBtnPrikaziKupca() {
        return btnPrikaziKupca;
    }

    public void setBtnPrikaziKupca(JButton btnPrikaziKupca) {
        this.btnPrikaziKupca = btnPrikaziKupca;
    }


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnObrisiKupca;
    private javax.swing.JButton btnPretraziKupca;
    private javax.swing.JButton btnPrikaziKupca;
    private javax.swing.JButton btnPromeniKupca;
    private javax.swing.JComboBox<Object> cmbMuzickoObrazovanje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKupac;
    private javax.swing.JTextField txtImePrezime;
    // End of variables declaration//GEN-END:variables
}
