/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author pavle
 */
public class PrikaziRacunForma extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrikaziRacunForma.class.getName());

    /**
     * Creates new form PrikaziRacunForma
     */
    public PrikaziRacunForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblRacun = new javax.swing.JTable();
        btnPromeniRacun = new javax.swing.JButton();
        btnNazad = new javax.swing.JButton();
        cmbProdavac = new javax.swing.JComboBox<>();
        txtUkupanIznos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbKupac = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtDatumIzdavanja = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbNacinPlacanja = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtPopust = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnPretraziRacun = new javax.swing.JButton();
        btnPrikaziRacun = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblRacun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRacun);

        btnPromeniRacun.setText("Promeni izabrani račun");
        btnPromeniRacun.addActionListener(this::btnPromeniRacunActionPerformed);

        btnNazad.setText("Nazad");

        cmbProdavac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Kupac:");

        cmbKupac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Datum izdavanja:");

        jLabel4.setText("Način plaćanja:");

        cmbNacinPlacanja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Popust:");

        jLabel1.setText("Prodavac:");

        jLabel6.setText("Ukupan iznos:");

        btnPretraziRacun.setText("Pretraži račune");

        btnPrikaziRacun.setText("Prikaži izabrani račun");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbProdavac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbKupac, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUkupanIznos)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDatumIzdavanja)
                                .addComponent(cmbNacinPlacanja, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPopust, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPretraziRacun))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnNazad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPrikaziRacun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPromeniRacun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbProdavac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtDatumIzdavanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbKupac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(cmbNacinPlacanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPopust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnPretraziRacun)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(btnPrikaziRacun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPromeniRacun)
                    .addComponent(btnNazad))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPromeniRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromeniRacunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPromeniRacunActionPerformed

    public JButton getBtnNazad() {
        return btnNazad;
    }

    public void setBtnNazad(JButton btnNazad) {
        this.btnNazad = btnNazad;
    }

    public JButton getBtnPromeniRacun() {
        return btnPromeniRacun;
    }

    public void setBtnPromeniRacun(JButton btnPromeniRacun) {
        this.btnPromeniRacun = btnPromeniRacun;
    }

    public JTable getTblRacun() {
        return tblRacun;
    }

    public void setTblRacun(JTable tblRacun) {
        this.tblRacun = tblRacun;
    }

    public JButton getBtnPretraziRacun() {
        return btnPretraziRacun;
    }

    public void setBtnPretraziRacun(JButton btnPretraziRacun) {
        this.btnPretraziRacun = btnPretraziRacun;
    }

    public JComboBox<Object> getCmbKupac() {
        return cmbKupac;
    }

    public void setCmbKupac(JComboBox<Object> cmbKupac) {
        this.cmbKupac = cmbKupac;
    }

    public JComboBox<Object> getCmbNacinPlacanja() {
        return cmbNacinPlacanja;
    }

    public void setCmbNacinPlacanja(JComboBox<Object> cmbNacinPlacanja) {
        this.cmbNacinPlacanja = cmbNacinPlacanja;
    }

    public JComboBox<Object> getCmbProdavac() {
        return cmbProdavac;
    }

    public void setCmbProdavac(JComboBox<Object> cmbProdavac) {
        this.cmbProdavac = cmbProdavac;
    }

    public JTextField getTxtDatumIzdavanja() {
        return txtDatumIzdavanja;
    }

    public void setTxtDatumIzdavanja(JTextField txtDatumIzdavanja) {
        this.txtDatumIzdavanja = txtDatumIzdavanja;
    }

    public JTextField getTxtPopust() {
        return txtPopust;
    }

    public void setTxtPopust(JTextField txtPopust) {
        this.txtPopust = txtPopust;
    }

    public JTextField getTxtUkupanIznos() {
        return txtUkupanIznos;
    }

    public void setTxtUkupanIznos(JTextField txtUkupanIznos) {
        this.txtUkupanIznos = txtUkupanIznos;
    }

    public JButton getBtnPrikaziRacun() {
        return btnPrikaziRacun;
    }

    public void setBtnPrikaziRacun(JButton btnPrikaziRacun) {
        this.btnPrikaziRacun = btnPrikaziRacun;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnPretraziRacun;
    private javax.swing.JButton btnPrikaziRacun;
    private javax.swing.JButton btnPromeniRacun;
    private javax.swing.JComboBox<Object> cmbKupac;
    private javax.swing.JComboBox<Object> cmbNacinPlacanja;
    private javax.swing.JComboBox<Object> cmbProdavac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRacun;
    private javax.swing.JTextField txtDatumIzdavanja;
    private javax.swing.JTextField txtPopust;
    private javax.swing.JTextField txtUkupanIznos;
    // End of variables declaration//GEN-END:variables
}
