/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import javax.swing.JButton;
import javax.swing.JSpinner;

/**
 *
 * @author pavle
 */
public class UbaciSmenuForma extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UbaciSmenuForma.class.getName());

    /**
     * Creates new form UbaciSmenuForma
     */
    public UbaciSmenuForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPocetakSmene = new javax.swing.JSpinner();
        txtKrajSmene = new javax.swing.JSpinner();
        btnUbaciSmenu = new javax.swing.JButton();
        btnNazad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Početak smene:");

        jLabel2.setText("Kraj smene:");

        txtPocetakSmene.setModel(new javax.swing.SpinnerNumberModel(8, 8, 16, 1));

        txtKrajSmene.setModel(new javax.swing.SpinnerNumberModel(12, 12, 20, 1));

        btnUbaciSmenu.setText("Ubaci smenu");

        btnNazad.setText("Nazad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPocetakSmene)
                            .addComponent(txtKrajSmene)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnNazad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addComponent(btnUbaciSmenu)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPocetakSmene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKrajSmene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUbaciSmenu)
                    .addComponent(btnNazad))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnNazad() {
        return btnNazad;
    }

    public void setBtnNazad(JButton btnNazad) {
        this.btnNazad = btnNazad;
    }

    public JButton getBtnUbaciSmenu() {
        return btnUbaciSmenu;
    }

    public void setBtnUbaciSmenu(JButton btnUbaciSmenu) {
        this.btnUbaciSmenu = btnUbaciSmenu;
    }

    public JSpinner getTxtKrajSmene() {
        return txtKrajSmene;
    }

    public void setTxtKrajSmene(JSpinner txtKrajSmene) {
        this.txtKrajSmene = txtKrajSmene;
    }

    public JSpinner getTxtPocetakSmene() {
        return txtPocetakSmene;
    }

    public void setTxtPocetakSmene(JSpinner txtPocetakSmene) {
        this.txtPocetakSmene = txtPocetakSmene;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnUbaciSmenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner txtKrajSmene;
    private javax.swing.JSpinner txtPocetakSmene;
    // End of variables declaration//GEN-END:variables
}
